# https://github.com/marketplace/actions/run-eslint

name: Lint CI
on:
  pull_request:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run lint -- src
